import type { FarmTemplate, ProductDraft } from "@/lib/types";

export function buildFarmTemplate(draft: ProductDraft): FarmTemplate {
  return {
    schemaVersion: 2,
    id: "TODO",
    title: "TODO",
    farmTypes: [{ id: "TODO", lt: "TODO", en: "TODO" }],
    locationNameNormalised: "TODO",
    titleNormalised: "TODO",
    descriptionLt: draft.descriptionLt,
    coordinates: { latitude: null, longitude: null },
    fullAddress: "TODO",
    postalCode: "TODO",
    openNow: false,
    contact: { email: "TODO", phone: "TODO" },
    links: [
      { type: "eshop", url: "TODO" },
      { type: "facebook", url: "TODO" },
      { type: "instagram", url: "TODO" },
      { type: "website", url: "TODO" },
      { type: "youtube", url: "TODO" },
    ],
    images: [],
    productCategories: {},
    services: {
      products: true,
      delivery: false,
      food: false,
      education: false,
      events: false,
      onSite: false,
      partnerships: false,
    },
    openHoursStructured: {
      monday: null,
      tuesday: null,
      wednesday: null,
      thursday: null,
      friday: null,
      saturday: null,
      sunday: null,
    },
    searchKeywords: [],
    averageRating: 0,
    ratingCount: 0,
    ratingTotal: 0,
    favouritesCount: 0,
    createdAt: "TODO_ISO_TIMESTAMP",
    updatedAt: "TODO_ISO_TIMESTAMP",
    createdBy: "TODO",
    ownerUserId: "TODO",
  };
}
